apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/frontend
  - base/github-proxy
  - base/gitserver
  - base/indexed-search
  - base/pgsql
  - base/precise-code-intel
  - base/query-runner
  - base/redis
  - base/replacer
  - base/repo-updater
  - base/searcher
  - base/symbols
  - base/syntect-server
