apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  template:
    spec:
      initContainers:
        - name: transfer-file-ownership
          image: alpine
          command: ["sh", "-c", "chown -R 100:100 /prometheus"]
          volumeMounts:
            - mountPath: /prometheus
              name: data
          securityContext:
            runAsUser: 0
